### ISSUE TITLE
create outb file with raw data using python

### ISSUE THREAD

**Issue by hugocastroo** [OpenFAST/python-toolbox#16]
I am completely new in the OpenFAST world and have been looking for information but haven't found anything in the readthedocs related to my topic.

I am working on a research project and I am getting raw data directly from a turbine and a Lidar sensor and I would like to generate an outb file with this data so that this data can be used in Matlab using the ReadFASTbinary.m script from the matlab-toolbox or displayed in the pyDatView if possible. 

Let's say I have the information about the following signals with more than 1000 elements for signal: Wind1VelX, Wind1VelY, Wind1VelZ, Azimuth, and RtSpeed. I would like to store this information in a outb file that I want to generate using python, is there any possibility for doing this?

Sorry if the question is not related or if I have overseen this information!

**Comment by ebranlard** [comment]
Hi @hugocastroo, unfortunately we don't a script that I know of to write in the binary format of openfast. 
There is a writer for the ascii format here: (and if we write a binary writer we should put it there as well) 
  https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/fast_output_file.py#L90 
Unfortunately it will expect you to have defined the "info", "data" fields of the object.  Looking into this script, I think it does need a bit of cleanup. 

Are you looking to export in binary or are you fine with ascii? Binary does have the advantage of saving disk space. If you are fine with ASCII, pyDatView/pyFAST can read csv, and openfast ascii .out.

If you are looking for a binary format, you can maybe use the format "parquet", which pyDatView supports. 
See for instance  https://github.com/ebranlard/weio/blob/b1addf69acf817ec42de62711dd8dff94c8e9f4b/weio/parquet_file.py

Have a python writer for fast binary files would be great. If you have the time to give it a try (based on the reader), that would be great!

**Comment by hugocastroo** [comment]
Hi @ebranlard ,  we are sampling our data at 4 Hz and after a couple of hours we have pretty much data, that is why we wanted to keep it in binary to take advantage of this saving disk space! 

For now, I don't think that I would have the time to make this writer for fast binary files but maybe I could connect it with a future project! I will let you know in case that I come to it! 

Thanks for your help!

**Comment by hugocastroo** [comment]
A couple of questions came to my mind:

I guess there must be a guideline for creating this outb file. I found the file "fastout_allnodes.outb", but still I wonder if there is some explanation about how to store the information in the file, I mean points like:
-How to separate the information (with , or % or just a blank space)
-what does the header file must contain, if there is a length limit for it etc.
-And in general the structure of the outb file.

How does normally the outb file is generated and populated with information?

Most of the things that I have seen are for reading the files but not really for creating/writing them. Is it needed to make a conversation from a file type to another one or how exactly does it work normally?

Thanks once again!

**Comment by ebranlard** [comment]
Hi @hugocastroo 

We might have a document giving the format specification, I'll try to find that. The main ideas of the format are as follows:
- it is a binary file
- some header data is stored at the beginning of the file, with no delimiter, you have to know where and what to read. For instance the file starts with a 16bit integer that identifies the format, then another one that specifies the number of channels
(see https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/fast_output_file.py#L238 )
- different headers are read depending on the file identifier. 
- Some file formats do not have the time vector in them, because time is a vector that can take small and large values, and it is not easy to store such vector that keep increasing without losing some resolution. 
- For some file ID, the channels are stored as "integer". To convert them to integer, you need first to remove the mean, and scale by the minimum and maximum. This is why in the reader, things are scaled on that line: https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/fast_output_file.py#L324


The way I would implement a writer would be to progressively write data to a binary file and try to read what you write, to verify that is the correct format. Your writer will more or less have the same structure as the reader, mostly replacing the "read" statements by "write". 

The writer of the TurbSim file, uses struct.pack to write to a binary file. 
https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/input_output/turbsim_file.py#L152
You could use this for inspiration too. 

I hope that helps.

**Comment by ebranlard** [comment]
Hi @hugocastroo, 
You can find a matlab script that write FAST binaries in the [matlab-toolbox](https://github.com/OpenFAST/matlab-toolbox/blob/main/Utilities/WriteFASTbinary.m), written by a colleague. From there, you could maybe convert this to python? Cheers,

**Comment by hugocastroo** [comment]
Hi @ebranlard , I wrote the code that I needed for python, and it is working fine, I have been using it in the last weeks, but it works just for writing files with FileID = 2. 

Cheers
[writeFastBinary2.py.txt](https://github.com/OpenFAST/python-toolbox/files/7661737/writeFastBinary2.py.txt)

**Comment by ebranlard** [comment]
Hi @hugocastroo 

Thanks for doing that. If would want to have authorship, maybe you can create a pull request for this? I would recommend putting your function at the end the of the file `input_output/fast_output_file.py`, putting your import statements at the top. 

Looking at the code, I would have a couple of suggestions:
- I think the interface of the function would be more natural if it uses a 2D-numpy array for channels instead of a list of arrays, such that `nT, numOutWithTime = np.shape(channels)` 
- If the min is equal to the max, the signal should be divided by one, to avoid a division by zero
- If you use a 2D numpy array for the channels, the range, scaling and offsets may be computed as numpy arrays without a for loop. (using `vrange =np.max(channels, axis=0), - np.min(channels, axis=1)`  and `vrange[vrange==0] =1 `)
- I'm guessing the transpose of memory of the packedData can also be done directly if a numpy array is used. 

If you don't have time to do the pull request, or to address some of these suggestion, it's no problem, just let me know and I can take care of it. 

Thanks again,

Emmanuel

**Comment by MeH-75** [comment]
Hi @ebranlard , I'm working on a collage project with python & need OpenFast python-toolbox to get data. but when I cd python-toolbox it shows an error that  you need an older version of python to install it. but after installing older versions I still get same error. I tried to install it on Linux and it worked but while I run the test cod with python  I'm getting errors and no result. can you please tell me how can I get  more detailed information about installing and working with python-toolbox

**Comment by ebranlard** [comment]
Hi @MeH-75 , 

I've never encountered this issue before. Can you start a new issue, describing what you have tried, which version of python you are using? Also, you can try to use the `dev` branch instead of the `main` branch just in case.  

Emmanuel

**Comment by MeH-75** [comment]
@ebranlard after adding path to system environment, I cd setup file but I encountered this error: UserWarning: The version specified ('"0.1.0"') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details
first I was using python 3.9 then I tried 3.8 but same thing happened.
actually I'm not very familiar with python cause I used Matlab much more, but now I'm working on a reinforcement learning project and I have to use python for this purpose

**Comment by ebranlard** [comment]
Hi @hugocastroo, I haven't heard from you so I've incorporated your script into `fast_output_file` and incorporated the changes I suggested. Thanks again for doing that!
