### ISSUE TITLE
how to install a downloaded python package in pyCharm

### ISSUE THREAD

**Issue by Unique-Wang** [OpenFAST/python-toolbox#18]
Dear @ebranlard ，

It's me again, I'm still struggling over the problem. It seems  if i wanna run your code ,a 'pyFAST' package is needed ,but no matter how many  times I tried,  like install and uninstall the package 'pyFAST', the warning is still there.

![image](https://user-images.githubusercontent.com/87693817/129820869-59f79628-fd68-4788-a1ef-e3d615befc34.png)
![image](https://user-images.githubusercontent.com/87693817/129820887-c8cdb8c8-8beb-4d0b-b40b-f6d355117ac7.png)
![1629249315(1)](https://user-images.githubusercontent.com/87693817/129820944-c4d73195-880b-4532-b47d-9567bbcf1485.png)
And I used this way to install pyFAST,I don't know where went wrong
![1629249544(1)](https://user-images.githubusercontent.com/87693817/129821217-1e10908e-1ed0-4e9f-81a9-62a5f084e74c.png)

Best regards,

**Comment by ebranlard** [comment]
Dear @Unique-Wang 

You'll have to uninstall the `pyFAST` that you installed because unfortunately the one available in pip [wheels](https://pypi.org/project/pyFAST/) is not our package. We'll have to look into that. 

In pyCharm, open a terminal, navigate to the folder where you downloaded the python-toolbox (using the command `cd` to change directoryies), and run the commands listed in the readme: 
```
python -m pip install -e .
```
Hopefully that would work. 

@MartinKoch-sowento is using pyCharm, maybe he can mention how he installed the python-toolbox.

**Comment by Unique-Wang** [comment]
Dear @ebranlard and @MartinKoch-sowento ,

I followed your instructions but unfortunately it did't work as I expected, and this is the screenshot I got 
![1629334235(1)](https://user-images.githubusercontent.com/87693817/129990532-c39cb64d-656e-4d31-a3a8-3bc3658755ab.png)
Thanks!

Best regards,

**Comment by ebranlard** [comment]
Hi @Unique-Wang ,  note that you have to type exactly the command I put, you'll see that there is a "dot" at the end. If you type pyFAST it's going to try to install the pyFAST from the pip wheels which is different. The "dot" indicates that pip will look in the current directory, which needs to be the base directory of the python-toolbox (the directory where README.md is located)

**Comment by Unique-Wang** [comment]
Dear @ebranlard ,

Yes ,it worked!!!!!!!!!! Thank you for being this patient!

Best Regards,

**Comment by ebranlard** [comment]
great!
