### ISSUE TITLE
Example_ExcelFile.py

### ISSUE THREAD

**Issue by tatesnow** [OpenFAST/python-toolbox#29]
when i run the code of Example_ExcelFile.py, the error occur

 dfs    = io.excel_file.ExcelFile(parametricFile).toDataFrame()
AttributeError: module 'pyFAST.input_output' has no attribute 'excel_file'

**Comment by ebranlard** [comment]
Hi @tatesnow 

The excel file reader was indeed missing. I've added it to the dev branch. It should work now. 
The example file in itself would only work if you have an openfast executable at the right location, and updated to the latest dev version of OpenFAST, since the data folder was updated to the latest dev format. 
But the feature using the Excel file is more or less independent of the version, so you could use it with your own openfast and corresponding input files.
