### ISSUE TITLE
Python based substitute for MLife and MExtremes

### ISSUE THREAD

**Issue by VishalSairam** [OpenFAST/python-toolbox#5]
Hello everyone.,

My name is Vishal, and I am a masters graduate from DTU Wind Energy in Denmark. I am working on aeroelastic simulations using openFAST, and the turbine models I am using are the WindPACT 1.5 and 5 MW turbines. I want to run DLCs 1.2 and 1.3, and for fatigue and ultimate calculations the tools available (MLife and MExtremes) are based in MATLAB. I would like to know if there are any substitutes for these tools which are python based and in general, some more python based tools for pre and post processing for openFAST simulations. 

Thank you! 

Best regards,
Vishal Sairam

**Comment by ptrbortolotti** [comment]
Dear Vishal,
at NREL we have developed the framework pCrunch (https://github.com/nrel/pcrunch), which you are welcome to use. It is not 100% ready, but you are welcome to try it and contribute to it.
I hope this helps,
Pietro

**Comment by VishalSairam** [comment]
Thank you for the quick reply Pietro! I will try it out now. 
Vishal

**Comment by VishalSairam** [comment]
Hi Pietro,

I have made my own script to run many simulation files for the 1.5 MW turbine, and have not used the WISDEM aeroelasticse tool. Can I still use the Analysis.py and Processing.py scripts to perform some fatigue calculations on the many .outb files I have? 

I am relatively new to python programming so any help would be highly appreciated.

Best regards,
Vishal

**Comment by ptrbortolotti** [comment]
Dear Vishal,
you can use pCrunch as part of WISDEM as well as a standalone tool. The jupyter notebook https://github.com/NREL/pCrunch/blob/master/batch_processing.ipynb should be relatively easy to use. At DTU many people know Python very very well and I am sure they can assist you. If you have any specific doubt about pCrunch, please post it there. I'm closing this issue here.
Best regards,
Pietro
