### ISSUE TITLE
Writing SubDyn input file issues with Member Output List

### ISSUE THREAD

**Issue by verlivkra** [OpenFAST/python-toolbox#51]
Hi, 
I am using the FASTInputFile class to make changes in a SubDyn-file. I am using the "5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth"-glue code as a test case. It seems like something goes wrong with the formatting of the member output list. Even when I am not changing anything, just reading the file and writing it, I get an error when running OpenFAST with the new generated files. 
The OpenFAST error says: 
_"FAST_InitializeAll:SD_Init:SD_Input: Error in file .\NRELOffshrBsline5MW_OC4Jacket_SubDyn.dat:
Failed to read member output list properties."_

Comparing the old and new subdyn-files, it seems there is an additional column that the FASTInputFile is not able to pass on to the new subdyn-file. 
Looking into the python-toolbox code, there are some comments regarding SubDyn using different formatting, but it is not clear to me how to fix it. I could give it a go if someone pointed me in the right direction.

**Comment by ebranlard** [comment]
Hi @verlivkra 
Thanks for reporting this!  I believe there were two issues with the writer, the first one was that the Members were written as float, and the second one was for the nodal outputs because it's not a "true" table since the number of headers and columns end up being different.  I've submitted a fix in the dev branch of this repository, let me know if it works.
