### ISSUE TITLE
Add functionality to create AMR-Wind sampling planes for FAST.Farm

### ISSUE THREAD

**Issue by rybchuk** [OpenFAST/python-toolbox#59]
Problem: At present, AMR-Wind modelers need to manually set up sampling fields for precursor simulations that will output info for FAST.Farm

Solution: Building off of #56, we will write code that takes several inputs (e.g., the farm layout, parameter sweeps) and outputs information that the AMR-Wind configuration file needs for FAST.Farm (e.g., location and spacing of the high-res and low res-sampling planes, frequency of output).

**Comment by ebranlard** [comment]
Hi @rybchuk 
Any scirpts that can ease the process for users are welcome, thanks for doing that! I'm guessing you'll coordinate with @rthedin ?

**Comment by rthedin** [comment]
That's right. I pushed some commits yesterday to #56 with some additional information for Alex.
We're also working on automatic computation of `ds_{low,high}` and `dt_{low,high}` instead of requiring the user to give these quantities. I don't think we have that coded up anywhere, but if you have already written something like that somewhere else that we're missing, please let us know.

**Comment by ebranlard** [comment]
I think some of the guidelines are implemented [here](https://github.com/OpenFAST/python-toolbox/blob/main/pyFAST/fastfarm/fastfarm.py#L207) from line 207 to 230:
Maybe that can help a tiny bit. But I'm sure you can come up with something better.

**Comment by rthedin** [comment]
Functionality in place as of https://github.com/OpenFAST/python-toolbox/pull/56/commits/9d24cf553905207c20ef4ee935f29b4d3fb72bfd.

To-do item
- [ ] Create the wind direction sweep and make the refinements general, removing the `0deg` hardcoded string [here](https://github.com/OpenFAST/python-toolbox/blob/9d24cf553905207c20ef4ee935f29b4d3fb72bfd/pyFAST/fastfarm/AMRWindSimulation.py#L120)
